export const CATEGORY_FILTER_OPTIONS = [
  "Publication",
  "Conference",
  "Workshop",
  "FDP",
  "Book",
  "NPTEL",
  "Seminar",
  "Webinar",
  "GuestLecture",
  "HonorsAwards",
  "Certification",
  "ResearchPolicy",
  "ProfessionalMembership",
  "IPR",
  "Consultancy",
  "Incubation",
  "ResearchProject",
  "DoctoralThesis",
  "MOU",
  "Others",
];

export const CATEGORY_LABELS = {
  Publication: "Publications",
  Conference: "Conferences",
  Workshop: "Workshops",
  FDP: "FDP",
  Book: "Books",
  NPTEL: "NPTEL",
  Seminar: "Seminars",
  Webinar: "Webinars",
  GuestLecture: "Guest Lectures",
  HonorsAwards: "Awards",
  Certification: "Certifications",
  ResearchPolicy: "Research Policy",
  ProfessionalMembership: "Memberships",
  IPR: "IPR",
  Consultancy: "Consultancy",
  Incubation: "Incubation",
  ResearchProject: "Projects",
  DoctoralThesis: "Doctoral Thesis",
  MOU: "MOUs",
  Others: "Others",
};
